USE Monitor_Host;

ALTER TABLE DeviceTypes
	MODIFY COLUMN DeviceTypeName VARCHAR(128),
	MODIFY COLUMN IconFile VARCHAR(128);

ALTER TABLE ConfiguratedDevices
	MODIFY COLUMN Address64 VARCHAR(64);

ALTER TABLE DeviceTypeChannels
	MODIFY COLUMN ChannelName VARCHAR(128),
	MODIFY COLUMN MinValue DOUBLE PRECISION,
	MODIFY COLUMN MaxValue DOUBLE PRECISION,
	MODIFY COLUMN UnitOfMeasurement VARCHAR(64);

ALTER TABLE Devices
	MODIFY COLUMN Address128 VARCHAR(64),
	MODIFY COLUMN Address64 VARCHAR(64);

ALTER TABLE DeviceChannels
	MODIFY COLUMN ChannelName VARCHAR(128),
	MODIFY COLUMN MinValue DOUBLE PRECISION,
	MODIFY COLUMN MaxValue DOUBLE PRECISION,
	MODIFY COLUMN UnitOfMeasurement VARCHAR(64);

ALTER TABLE DeviceLinkParameters
	MODIFY COLUMN ParameterValue VARCHAR(64);

ALTER TABLE DeviceReadings
	MODIFY COLUMN Value VARCHAR(64);

ALTER TABLE DeviceBatteryStatistics
	MODIFY COLUMN BatteryLevel DOUBLE PRECISION,
	MODIFY COLUMN RemainingBatteryHours DOUBLE PRECISION;

ALTER TABLE Commands
	MODIFY COLUMN ErrorReason VARCHAR(256),
	MODIFY COLUMN Response VARCHAR(256);

ALTER TABLE CommandParameters
	MODIFY COLUMN ParameterValue VARCHAR(64);

ALTER TABLE Firmwares
	MODIFY COLUMN FileName VARCHAR(256);

ALTER TABLE Properties
	MODIFY COLUMN `Key` VARCHAR(64),
	MODIFY COLUMN Value VARCHAR(64);

ALTER TABLE Users
	MODIFY COLUMN UserName VARCHAR(64),
	MODIFY COLUMN FirstName VARCHAR(64),
	MODIFY COLUMN LastName VARCHAR(64),
	MODIFY COLUMN Email VARCHAR(128),
	MODIFY COLUMN Password VARCHAR(256);

ALTER TABLE Companies
	MODIFY COLUMN CompanyName VARCHAR(256),
	MODIFY COLUMN LogoFile VARCHAR(128);

ALTER TABLE LocalControlLoops
	MODIFY COLUMN LowThreshold DOUBLE PRECISION,
	MODIFY COLUMN HighThreshold DOUBLE PRECISION;

ALTER TABLE DeviceConnections
	MODIFY COLUMN IP VARCHAR(64);


DELETE FROM Properties WHERE `Key`='Version';
REPLACE INTO Properties(`Key`, Value) VALUES('SchemaVersion', '13.2.22');
REPLACE INTO Properties(`Key`, Value) VALUES('DataVersion', '13.2.22');